/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedEspnRouteImport } from './routes/_authenticated.espn'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated.history'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated.insights'
import { Route as AuthenticatedLeaguesNewRouteImport } from './routes/_authenticated.leagues.new'
import { Route as PublicSharedHistoryRouteImport } from './routes/_public.shared.history'
import { Route as PublicSharedInsightsRouteImport } from './routes/_public.shared.insights'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEspnRoute = AuthenticatedEspnRouteImport.update({
  id: '/espn',
  path: '/espn',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaguesNewRoute = AuthenticatedLeaguesNewRouteImport.update({
  id: '/leagues/new',
  path: '/leagues/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicSharedHistoryRoute = PublicSharedHistoryRouteImport.update({
  id: '/shared/history',
  path: '/shared/history',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSharedInsightsRoute = PublicSharedInsightsRouteImport.update({
  id: '/shared/insights',
  path: '/shared/insights',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/health': typeof HealthRoute
  '/espn': typeof AuthenticatedEspnRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/leagues/new': typeof AuthenticatedLeaguesNewRoute
  '/shared/history': typeof PublicSharedHistoryRoute
  '/shared/insights': typeof PublicSharedInsightsRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/health': typeof HealthRoute
  '/espn': typeof AuthenticatedEspnRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/leagues/new': typeof AuthenticatedLeaguesNewRoute
  '/shared/history': typeof PublicSharedHistoryRoute
  '/shared/insights': typeof PublicSharedInsightsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/health': typeof HealthRoute
  '/_authenticated/espn': typeof AuthenticatedEspnRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/leagues/new': typeof AuthenticatedLeaguesNewRoute
  '/_public/shared/history': typeof PublicSharedHistoryRoute
  '/_public/shared/insights': typeof PublicSharedInsightsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/espn'
    | '/history'
    | '/insights'
    | '/leagues/new'
    | '/shared/history'
    | '/shared/insights'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/espn'
    | '/history'
    | '/insights'
    | '/leagues/new'
    | '/shared/history'
    | '/shared/insights'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/health'
    | '/_authenticated/espn'
    | '/_authenticated/history'
    | '/_authenticated/insights'
    | '/_authenticated/'
    | '/_authenticated/leagues/new'
    | '/_public/shared/history'
    | '/_public/shared/insights'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  HealthRoute: typeof HealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/espn': {
      id: '/_authenticated/espn'
      path: '/espn'
      fullPath: '/espn'
      preLoaderRoute: typeof AuthenticatedEspnRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leagues/new': {
      id: '/_authenticated/leagues/new'
      path: '/leagues/new'
      fullPath: '/leagues/new'
      preLoaderRoute: typeof AuthenticatedLeaguesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/shared/history': {
      id: '/_public/shared/history'
      path: '/shared/history'
      fullPath: '/shared/history'
      preLoaderRoute: typeof PublicSharedHistoryRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/shared/insights': {
      id: '/_public/shared/insights'
      path: '/shared/insights'
      fullPath: '/shared/insights'
      preLoaderRoute: typeof PublicSharedInsightsRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedEspnRoute: typeof AuthenticatedEspnRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedLeaguesNewRoute: typeof AuthenticatedLeaguesNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedEspnRoute: AuthenticatedEspnRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedLeaguesNewRoute: AuthenticatedLeaguesNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicSharedHistoryRoute: typeof PublicSharedHistoryRoute
  PublicSharedInsightsRoute: typeof PublicSharedInsightsRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicSharedHistoryRoute: PublicSharedHistoryRoute,
  PublicSharedInsightsRoute: PublicSharedInsightsRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  HealthRoute: HealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
